RezervacijaSoba/RezervacijaSoba/Models/Smestaj.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace RezervacijaSoba.Models
{
    public class Smestaj
    {
        public int Id { get; set; }

        [Required]
        [StringLength(20)]
        [Display(Name="Name")]
        public string Naziv { get; set; }

        [Required]
        [StringLength(20)]
        [Display(Name = "Description")]
        public string Opis { get; set; }

        [Required]
        [StringLength(20)]
        [Display(Name = "Adress")]
        public string Adresa { get; set; }

        [Required]
        [Display(Name = "Rating")]
        public double Ocena { get; set; }

        public List<Soba> ListSoba { get; set; }
    }
}

RezervacijaSoba/RezervacijaSoba/Controllers/RezervacijasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RezervacijaSoba.Models;

namespace RezervacijaSoba.Controllers
{
    public class RezervacijasController : Controller
    {
        private RezervacijaContext db = new RezervacijaContext();

        // GET: Rezervacijas
        public ActionResult Index()
        {
            var rezervacija = db.Rezervacija.Include(r => r.Soba);
            return View(rezervacija.ToList());
        }

        // GET: Rezervacijas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rezervacija rezervacija = db.Rezervacija.Find(id);
            if (rezervacija == null)
            {
                return HttpNotFound();
            }
            return View(rezervacija);
        }

        // GET: Rezervacijas/Create
        public ActionResult Create(int id)
        {

            ViewBag.SobaId = id;
            return View();
        }

        // POST: Rezervacijas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,ImePrezime,Od,Do,Otkazana,SobaId")] Rezervacija rezervacija)
        {
            if (ModelState.IsValid)
            {
                db.Rezervacija.Add(rezervacija);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.SobaId = new SelectList(db.Soba, "Id", "Id", rezervacija.SobaId);
            return View(rezervacija);
        }

        // GET: Rezervacijas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rezervacija rezervacija = db.Rezervacija.Find(id);
            if (rezervacija == null)
            {
                return HttpNotFound();
            }
            ViewBag.SobaId = new SelectList(db.Soba, "Id", "Id", rezervacija.SobaId);
            return View(rezervacija);
        }

        // POST: Rezervacijas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,ImePrezime,Od,Do,Otkazana,SobaId")] Rezervacija rezervacija)
        {
            if (ModelState.IsValid)
            {
                db.Entry(rezervacija).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.SobaId = new SelectList(db.Soba, "Id", "Id", rezervacija.SobaId);
            return View(rezervacija);
        }

        // GET: Rezervacijas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rezervacija rezervacija = db.Rezervacija.Find(id);
            if (rezervacija == null)
            {
                return HttpNotFound();
            }
            return View(rezervacija);
        }

        // POST: Rezervacijas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Rezervacija rezervacija = db.Rezervacija.Find(id);
            db.Rezervacija.Remove(rezervacija);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RezervacijaSoba/RezervacijaSoba/Controllers/SmestajsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using RezervacijaSoba.Models;
using RezervacijaSoba.ViewModel;

namespace RezervacijaSoba.Controllers
{
    public class SmestajsController : Controller
    {
        private RezervacijaContext db = new RezervacijaContext();

        public enum SortType
        {
            Name,
            NameDesc,
            Rating,
            RatingDesc,
        }

        public static Dictionary<string, SortType> SortTypeDict = new Dictionary<string, SortType>
        {
            {"Name", SortType.Name },
            {"NameDesc", SortType.NameDesc },
            {"Rating", SortType.Rating },
            {"RatingDesc", SortType.RatingDesc },
        };


        // GET: Smestajs
        public ActionResult Index(string sortType = "Name")
        {
            SortType sortBy = SortTypeDict[sortType];

            IQueryable<Smestaj> list = db.Smestaj;

            switch (sortBy)
            {
                case SortType.Name:
                    list = list.OrderBy(p => p.Naziv);
                    break;
                case SortType.NameDesc:
                    list = list.OrderByDescending(p => p.Naziv);
                    break;
                case SortType.Rating:
                    list = list.OrderBy(p => p.Ocena);
                    break;
                case SortType.RatingDesc:
                    list = list.OrderByDescending(p => p.Ocena);
                    break;
            }
            ViewBag.sortTypes = new SelectList(SortTypeDict, "key", "key", sortType);
            ViewBag.currentsortype = sortType;
            return View(list.ToList());
        }

        // GET: Smestajs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Smestaj smestaj = db.Smestaj.Find(id);
            if (smestaj == null)
            {
                return HttpNotFound();
            }
            SmestajListaSobaViewModel vm = new SmestajListaSobaViewModel();
            vm.Smestaj = smestaj;
            vm.ListaSoba = db.Soba.Where(p => p.SmestajId == id).ToList();
            return View(vm);
        }

        // GET: Smestajs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Smestajs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Naziv,Opis,Adresa,Ocena")] Smestaj smestaj)
        {
            if (ModelState.IsValid)
            {
                db.Smestaj.Add(smestaj);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(smestaj);
        }

        // GET: Smestajs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Smestaj smestaj = db.Smestaj.Find(id);
            if (smestaj == null)
            {
                return HttpNotFound();
            }
            return View(smestaj);
        }

        // POST: Smestajs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Naziv,Opis,Adresa,Ocena")] Smestaj smestaj)
        {
            if (ModelState.IsValid)
            {
                db.Entry(smestaj).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(smestaj);
        }

        // GET: Smestajs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Smestaj smestaj = db.Smestaj.Find(id);
            if (smestaj == null)
            {
                return HttpNotFound();
            }
            return View(smestaj);
        }

        // POST: Smestajs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Smestaj smestaj = db.Smestaj.Find(id);
            db.Smestaj.Remove(smestaj);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Filter(SmestajFilter filter)
        {
            IQueryable<Smestaj> smestaj = db.Smestaj;

            if (!filter.Adresa.IsNullOrWhiteSpace())
            {
                smestaj = smestaj.Where(p => p.Adresa.Contains(filter.Adresa));
            }

            if (!filter.Opis.IsNullOrWhiteSpace())
            {
                smestaj = smestaj.Where(p => p.Opis.Contains(filter.Opis));
            }

            return View(smestaj.ToList());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RezervacijaSoba/RezervacijaSoba/Views/Smestajs/Create.cshtml
@model RezervacijaSoba.Models.Smestaj

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Smestaj</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Naziv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Naziv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Naziv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Opis, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Opis, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Opis, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Adresa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Adresa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Adresa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ocena, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ocena, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ocena, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RezervacijaSoba/RezervacijaSoba/Views/Smestajs/Delete.cshtml
@model RezervacijaSoba.Models.Smestaj

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Smestaj</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Naziv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Naziv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Opis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Opis)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Adresa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Adresa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ocena)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ocena)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

RezervacijaSoba/RezervacijaSoba/Views/Smestajs/Details.cshtml
@model RezervacijaSoba.ViewModel.SmestajListaSobaViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Smestaj</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Smestaj.Naziv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Smestaj.Naziv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Smestaj.Opis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Smestaj.Opis)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Smestaj.Adresa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Smestaj.Adresa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Smestaj.Ocena)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Smestaj.Ocena)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Smestaj.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

<h2>Lista soba ovog smestaja</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Smestaj.Naziv)
        </th>
        <th>
            @Html.DisplayName("Broj Sobe")
        </th>
        <th>
            @Html.DisplayName("Broj kreveta")
        </th>
        <th>
            @Html.DisplayName("Cena po nocenju")
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model.ListaSoba)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Smestaj.Naziv)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BrojSobe)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BrojKreveta)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CenaPoNocenju)
            </td>
            <td>
                @Html.ActionLink("Rezervisi sobu", "Create", "Rezervacijas", new { id = item.Id},null ) 
            </td>
        </tr>
    }
</table>

RezervacijaSoba/RezervacijaSoba/Views/Smestajs/Edit.cshtml
@model RezervacijaSoba.Models.Smestaj

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Smestaj</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Naziv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Naziv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Naziv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Opis, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Opis, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Opis, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Adresa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Adresa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Adresa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ocena, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ocena, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ocena, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RezervacijaSoba/RezervacijaSoba/Views/Smestajs/Filter.cshtml
@model IEnumerable<RezervacijaSoba.Models.Smestaj>

@{
    ViewBag.Title = "Filter";
}

<h2>Filter Results</h2>
@Html.ActionLink("Go Back", "Index")

@{
    Html.RenderPartial("_SmestajList");
}

RezervacijaSoba/RezervacijaSoba/Views/Smestajs/Index.cshtml
@model IEnumerable<RezervacijaSoba.Models.Smestaj>
@{
    ViewBag.Title = "Index";
}
<h2>Lista smestaja</h2>
<p class="clearfix">
    @Html.ActionLink("Create New", "Create")
    <button id="filter" class="btn btn-default btn-lg pull-right">Filter</button>
</p>

<div id="filterForm" class="hidden">
    @using (Html.BeginForm("FIlter", "Smestajs", FormMethod.Post))
    {
        @Html.Label("Description")
        @Html.TextBox("Opis", null, new { @class = "form*control" })
        @Html.Label("address")
        @Html.TextBox("Adresa", null, new { @class = "form*control" })
        <input type="submit" class="btn btn-info" />
    }
</div>

<div class="well clearfix">
    <div class="col-md-6">
        <span>Sortiraj Smestaj</span>

        @using (Html.BeginForm("Index", "Smestajs", FormMethod.Post))
        {
            @Html.DropDownList("sortType", ViewBag.sortTypes as SelectList, new { @class = "form-control col-md-6" })
            <input type="submit" name="Sort">
        }
    </div>
</div>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Naziv)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Opis)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Adresa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ocena)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Naziv)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Opis)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Adresa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ocena)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }
</table>


@section scripts
{

    <script src="~/Scripts/myfilter.js"></script>
}

RezervacijaSoba/RezervacijaSoba/Views/Smestajs/_SmestajList.cshtml
@model IEnumerable<RezervacijaSoba.Models.Smestaj>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Naziv)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Opis)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Adresa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ocena)
        </th>
        <th></th>
    </tr>

    @foreach(var item in Model)
    {
        Html.RenderPartial("_Smestajitem", item);
    }



</table>

RezervacijaSoba/RezervacijaSoba/Views/Smestajs/_Smestajitem.cshtml
@model RezervacijaSoba.Models.Smestaj

<tr>
    <td>
        @Model.Naziv
    </td>
    <td>
         @Model.Opis
    </td>
    <td>
        @Model.Adresa
    </td>
    <td>
        @Model.Ocena
    </td>
    
</tr>